stages:
  - build

build-job:
  stage: build

  tags:
    - nodejs

  before_script:
    - apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser

  script:
    - npm install
    - npm install -g @angular/cli@11.2.11
    - ng build
    - ng lint
    - ng test
