cache:
  paths:
    - node_modules/
    - dist/

default:
  image: atlassianlabs/docker-node-jdk-chrome-firefox


stages:
  - install
  - test
  - build
  - deploy

install_job:
  stage: install

  tags:
    - dapp

  script:
    - npm ci
    - npm install -g @angular/cli@11.2.11

  only:
    - merge_requests

lint_job:
  stage: test

  tags:
    - dapp

  script:
    - npm run lint

  only:
    - merge_requests

karma_job:
  stage: test

  tags:
    - dapp

  script:
    - npm run test:ci

  only:
    - merge_requests

build_job:
  stage: build

  tags:
    - dapp

  script:
    - npm run build
    - ln


  only:
    - master



deploy_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  tags:
    - dapp

  script:
    - aws s3 sync --delete ./dist/dapp s3://coop-wallet

  only:
    - master
