stages:
  - install
  - build

install-job:
  stage: install
  image: local-nodejs:12
  tags:
    - npm
  script:
    - npm ci


build-job:
  stage: build
  image: local-nodejs:12
  tags:
    - npm
  script:
    - npm install -g @angular/cli 
    - ng build
