cache:
  paths:
    - node_modules/

default:
  image: atlassianlabs/docker-node-jdk-chrome-firefox


stages:
  - install
  - test
  - build

install_job:
  stage: install

  tags:
    - dapp

  script:
    - npm ci

lint_job:
  stage: test

  tags:
    - dapp

  script:
    - npm run lint

karma_job:
  stage: test

  tags:
    - dapp

  script:
    - npm run test:ci

build_job:
  stage: build

  tags:
    - dapp

  script:
    - ng build
