stages:
  - install
  - build

install-job:
  stage: install
  tags:
    - npm
  script:
    - npm ci


build-job:
  stage: build
  tags:
    - nodejs
  script:
    - node --version
    - npm install -g @angular/cli 
    - ng build
