cache:
  paths:
    - node_modules/

default:
  image: atlassianlabs/docker-node-jdk-chrome-firefox


stages:
  - install
  - test
  - buildtest

install_job:
  stage: install

  tags:
    - dapp

  script:
    - npm ci

  only:
    - merge_requests
    - pushes
    - master

lint_job:
  stage: test

  tags:
    - dapp

  script:
    - npm run lint

  only:
    - merge_requests
    - pushes

karma_job:
  stage: test

  tags:
    - dapp

  script:
    - npm run test:ci

  only:
    - merge_requests

buildtest_job:
  stage: buildtest

  tags:
    - dapp

  script:
    - npm install -g @angular/cli@11.2.11
    - ng build


