stages:
  - build

build-job:
  stage: build
  image: browserless/chrome
  before_script:
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm install
    - npm install -g @angular/cli@11.2.11
    - ng build
    - ng lint
