stages:
  - install
  - build

install-job:
  stage: install
  tags:
    - npm
  script:
    - npm ci


build-job:
  stage: build
  tags:
    - nodejs
  script:
    - npm install -g @angular/cli@11.2.11
    - ng build
