default:
  image: atlassianlabs/docker-node-jdk-chrome-firefox

stages:
  - build

build-job:
  stage: build



  script:
    - npm install
    - npm install -g @angular/cli@11.2.11
    - ng build
    - ng lint
